osx_image: xcode7.3
language: objective-c

script:
- xcodebuild -workspace Playground/Playground.xcworkspace -scheme 'UnitTests' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' test